### PR TITLE
Fix multi-shift action location title bug.

### LINKED ISSUE #60: MultiShiftActionForm location rendered as "title"
When displaying events in a campaign, the location is sometimes being shown as just "title" not the location name despite it being returned in the API reponse:

# Expected Behaviour

All events listed on campaign pages like this: https://www.zetk.in/o/633/campaigns/1868 have a location listed that matches the location of the event:

Screenshot from 2023-07-11 14-14-16

# Actual Behaviour

"title" appears next to the location, seemingly only for multi shift events

Screenshot from 2023-07-11 14-00-03

# Possible solution

It looks like in line 94 of  `./campaignForm/action/MultiShiftActionForm.jsx` there need to be some `[]` s added to make it:

```js
let location = actions[0].getIn(['location', 'title']);
```

### PR DESCRIPTION
**Pull request by niklasva82**
Resolves #60 
image

### CODE REVIEW

File: campaignForm/action/MultiShiftActionForm.jsx [hunk 1]
```diff
@@ -91,7 +91,7 @@ export default class MultiShiftActionForm extends React.Component {
                     label={ currentNeedLabel }/>;
         }
 
-        let location = actions[0].getIn('location', 'title');
+        let location = actions[0].getIn(['location', 'title']);
```
Comment (richardolsson) [inline campaignForm/action/MultiShiftActionForm.jsx:94]: Oh what an annoying mistake. Nice catch! 💯

**Review by richardolsson — APPROVED** [review]
This looks good to me @niklasva82. Will you make sure that this version of common is included in www and call, even after merging several different PRs related to common?
